# Site settings
title: "Yaks All The Way Down"
logo: yak.png # image from https://www.flickr.com/photos/lwr/5496279831/in/set-72157594159055823
email: no-reply@yaks-all-the-way-down.com
description: Shave less yaks!
#url: "http://yaks-all-the-way-down.com" # the base hostname & protocol for your site
url: "/"
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: none
github_username:  none

#authors
authors:
  gharcombe-minson:
    name: Gareth Harcombe-Minson
    bio: Gamer. Oh and I code and stuff.
    thumb-img: garadox.png
  mcameron:
    name: Michael Cameron
    bio: TBD
    thumb-img: tbd.png
  jlane:
    name: Joe Lane
    bio: TBD
    thumb-img: tbd.png
  tednaleid:
    name: Ted Naleid
    bio: TBD
    thumb-img: tbd.png

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
